services:
  fwoapp:
    image: fwoapp
    container_name: fwoapp
    build: .
    volumes:
      - ${TRAINED_MODELS}:/trained_models
    environment:
      - DB_PORT=${DB_PORT}
      - DB_PWD=${DB_PWD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - VITE_URI_PRODUCTION=${VITE_URI_PRODUCTION}
      - FLASK_ENV=production
      - MODEL_TAG=${MODEL_TAG}

    ports:
      - 1000:5000
