version: '3.8'

services:
  fwoapp:
    image: fwoapp
    build: .
    volumes:
      # set this according to where your data folder located
      - ${DATA}:/app/src/data/
      - ${DATA}/.env:/app/.env

    ports:
      - 5000:5000

    env_file:
      - .env

    container_name: fwoapp
