services:
  fwoapp:
    image: fwoapp
    container_name: fwoapp
    build: .
    volumes:
      - ${TRAINED_MODELS}:/trained_models
    environment:
      - MODEL_POS_FORECASTING=${MODEL_POS_FORECASTING}
      - DIM_MEAL_EMBDS=${DIM_MEAL_EMBDS}
      - DIM_TOPK=${DIM_TOPK}
      - DB_PORT=${DB_PORT}
      - DB_PWD=${DB_PWD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - VITE_URI_PRODUCTION=${VITE_URI_PRODUCTION}
      - FLASK_ENV=production

    ports:
      - 1000:5000
