services:
  # fwoapp_frontend:
  #   image: fwoapp_fe
  #   container_name: fwoapp_fe
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile.FE
  #   volumes:
  #     - ${CODE}:/app
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - fwoapp_backend

  fwoapp_backend:
    image: fwoapp_be
    container_name: fwoapp_be
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.BE
    volumes:
      - ${DATA}:/app/src/data/
      - ${CODE}:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    ports:
      - 5000:5000
