version: '3.8'

services:
  fwoapp:
    image: fwo-backend
    build: .
    volumes:
    # set this according to where your data folder located
      - /home/Downloads/data:/src/data/basic_mvp_data
    ports:
      - 5000:5000
