version: '3.8'

services:
  fwoapp:
    image: fwoapp
    build: .
    volumes:
    # set this according to where your data folder located
      - ./data:/app/src/data/
    
    environment:
      DB_USER: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_HOSTNAME: /run/secrets/db_hostname
      DB_NAME: /run/secrets/db_name
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD_FILE}@${DB_HOSTNAME}/${DB_NAME}
      
    ports:
      - 5000:5000

    container_name: fwoapp

    secrets:
      - db_user
      - db_password
      - db_hostname
      - db_name


secrets:
  db_user:
    file: ./.secrets/db_user.txt
  db_password:
    file: ./.secrets/db_password.txt
  db_hostname:
    file: ./.secrets/db_hostname.txt
  db_name:
    file: ./.secrets/db_name.txt
