[tool.poetry]
name = "food-waste-reduction"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
invoke = "^2.2.0"
pandas = "^2.2.2"
scikit-learn = "^1.5.0"
matplotlib = "^3.9.0"
python-dotenv = "^1.0.1"
flask-cors = "^4.0.1"
flask-sqlalchemy = "^3.1.1"
psycopg2-binary = "^2.9.9"
loguru = "^0.7.2"
u8darts = {extras = ["notorch"], version = "^0.30.0"}
skl2onnx = "^1.17.0"
onnxruntime = "^1.18.1"
seaborn = "^0.13.2"
psycopg = "^3.2.2"



[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
coverage = "^7.5.3"
pylint = "^3.2.2"
flask-testing = "^0.8.1"
ipywidgets = "^8.1.3"
ipykernel = "^6.29.4"
ruff = "^0.4.10"
openpyxl = "^3.1.3"
seaborn = "^0.13.2"
pickleshare = "^0.7.5"
transformers = "^4.44.1"
torch = "^2.4.0"
nbformat = "^5.10.4"
levenshtein = "^0.25.1"
pyqt5 = "^5.15.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
