name: Deploy to production

on:
    release:
        types: [published]

jobs:
    tests:
        uses: ./.github/workflows/tests.yml
    
    build-and-push:
        runs-on: ubuntu-latest2
        #needs: tests

        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                    push: true
                    tags: ohjelmistotuotantoprojekti/food-waste-optimization:latest
