name: Deploy to production

on:
  release:
    types: [published]
  workflow_dispatch:
  # This enables backtracking to a previous release if needed
    inputs:
      release:
        description: 'Which release to use for building the container'
        required: true
        default: 'latest'

jobs:
# Return to these later, need to reconfigure tests.yml
#tests:
#    uses: ./.github/workflows/tests.yml

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get this release tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual input tag: ${{ github.event.inputs.release }}"
            echo "::set-output name=tag::${{ github.event.inputs.release }}"
          else
            echo "Release tag: ${{ github.ref_name }}"
            echo "::set-output name=tag::${{ github.ref_name }}"
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ohjelmistotuotantoprojekti/food-waste-optimization:${{ steps.get_tag.outputs.tag }}
            ohjelmistotuotantoprojekti/food-waste-optimization:latest
          build-args: |
            DB_USER=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ env.DB_HOST }}
            DB_NAME=${{ env.DB_NAME }}
