name: Deploy to production

on:
  release:
    types: [published]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to build the container from'
        required: true
        default: 'latest'
jobs:
    tests:
        uses: ./.github/workflows/tests.yml
    
    build-and-push:
        runs-on: ubuntu-latest2
        
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v2
              run: |
                docker build --build-arg DB_USER=${{ secrets.DB_USERNAME }} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                --build-arg DB_HOST=${{env.DB_HOST}} --build-arg DB_NAME=${{env.DB_NAME}} -t ohjelmistotuotantoprojekti/food-waste-optimization:latest .
                docker push ohjelmistotuotantoprojekti/food-waste-optimization:latest
