name: Deploy to staging

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    Build-and-push:
      name: Build and push application images to Docker Hub
      runs-on: ubuntu-latest
        
      steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: ohjelmistotuotantoprojekti/food-waste-optimization:staging
