name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Set environment variables
        run: |
          echo "DB_USER = ${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD = ${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOSTNAME = ${{ vars.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME = ${{ vars.DB_NAME }}" >> $GITHUB_ENV
          echo "DATABASE_URL = postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOSTNAME}/${{ vars.DB_NAME }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry lock && poetry install
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
        working-directory: src
      - name: Coverage report
        run: poetry run coverage xml
        working-directory: src
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Pylint
        run: poetry run pylint src
