name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOSTNAME: ${{ env.DB_HOST }}
      DB_NAME: ${{ env.DB_NAME }}
      DATABASE_URL : "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${DB_NAME}"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry lock && poetry install
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
        working-directory: src
      - name: Coverage report
        run: poetry run coverage xml
        working-directory: src
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Pylint
        run: poetry run pylint src
